name: Build & Deploy to Google Play

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Decode keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > upload.jks

      - name: Create Play service account json
        run: |
          echo '${{ secrets.PLAY_SERVICE_ACCOUNT_JSON }}' > play-service-account.json

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Upload to Play (Fastlane)
        env:
          KEYSTORE_PATH: ${{ github.workspace }}/upload.jks
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
          SUPPLY_JSON_KEY: ${{ github.workspace }}/play-service-account.json
        run: |
          chmod +x ./gradlew
          gem install fastlane -N --user-install
          echo "$HOME/.local/share/gem/ruby/3.2.0/bin" >> $GITHUB_PATH
          fastlane android deploy_internal
